# Generated by Django 6.0.5 on 2026-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.IntegerField()),
                ('container_type', models.CharField(max_length=50)),
                ('total_capacity', models.FloatField()),
                ('available_capacity', models.FloatField()),
                ('capacity_unit', models.CharField(max_length=20)),
                ('origin_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('provider_id', models.IntegerField()),
            ],
        ),
    ]
