# Generated by Django 6.0.5 on 2026-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='company',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
