# Generated by Django 5.2.14 on 2026-06-03 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceprovider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('pickup', 'Pickup'), ('tempo', 'Tempo'), ('van', 'Van'), ('bike', 'Bike'), ('other', 'Other')], default='truck', max_length=30)),
                ('weight_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('empty_space', models.CharField(max_length=150)),
                ('can_travel_upto', models.CharField(max_length=255)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_until', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='serviceprovider.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider Availability',
                'verbose_name_plural': 'Service Provider Availabilities',
                'ordering': ['-created_at'],
            },
        ),
    ]
