# Generated by Django 6.0.5 on 2026-06-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='account_type',
            field=models.CharField(default='serviceProvider', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='auth_provider',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_photo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
