# Generated by Django 6.0.5 on 2026-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100, unique=True)),
                ('transport_mode', models.CharField(choices=[('Ship', 'Ship'), ('Train', 'Train'), ('Truck', 'Truck'), ('Bus', 'Bus')], max_length=50)),
                ('container_type', models.CharField(max_length=50)),
                ('capacity_volume', models.FloatField()),
                ('capacity_weight', models.FloatField()),
                ('available_volume', models.FloatField()),
                ('available_weight', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Limited', 'Limited'), ('Full', 'Full'), ('In Transit', 'In Transit')], default='Available', max_length=50)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=50)),
                ('special_handling', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
